import { FunctionalComponent, SVGAttributes } from 'vue';

interface SVGProps extends Partial<SVGAttributes> {
  size?: 24 | number;
  strokeWidth?: number | string;
  absoluteStrokeWidth?: boolean;
}

export type Icon = FunctionalComponent<SVGProps>;

//icons
export {
  DatabaseIcon,
  NetworkIcon,
  LayoutTemplateIcon,
  Trash2Icon,
  UndoIcon,
  RedoIcon,
  RulerIcon,
  Grid3X3Icon,
  ZoomInIcon,
  ZoomOutIcon,
  ScalingIcon,
  ExpandIcon,
  ArrowBigLeftIcon,
  SearchIcon,
  LayoutDashboardIcon,
  ArrowDownIcon,
  ArrowUpIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ChevronDownIcon,
  Layers3Icon,
  PackageIcon,
  MonitorCheckIcon,
  Rows3Icon,
  FileJsonIcon,
  SquareMenuIcon,
  PlusIcon,
  CopyIcon,
  PencilLineIcon,
  ExternalLinkIcon,
  XIcon,
  EyeIcon,
  FileTextIcon,
  SaveIcon,
  ServerIcon,
  SquareFunctionIcon,
  ChevronsLeftRightIcon,
  ChevronsRightLeftIcon,
  ChevronsUpDownIcon,
  ChevronsDownUpIcon,
  InfoIcon,
  AppWindowIcon,
  SquareTerminalIcon,
  FileIcon,
  HomeIcon,
  EllipsisIcon,
  FolderOpenIcon,
  LayoutIcon,
  PaletteIcon,
  SquareIcon,
  BracesIcon,
  EclipseIcon,
  HelpCircleIcon,
  CrossIcon,
  ComponentIcon,
  PanelBottomIcon,
  DeleteIcon,
  CopyPlusIcon,
  PanelTopIcon,
  MessageSquareIcon,
  LogOutIcon,
  CloudIcon,
  GithubIcon,
  PlusCircleIcon,
  UserIcon,
  SettingsIcon,
  CreditCardIcon,
  PlusSquareIcon,
  MailIcon,
  CalendarIcon,
  TrashIcon,
  MinusIcon,
  SquareDashedBottomIcon,
  Maximize2Icon,
} from 'lucide-vue-next';
