export default {
  id: '',
  name: '开关',
  activeText: '',
  inactiveText: '',
  inlinePrompt: false,
  fontSize: 16,
  color: '#000000',
  activeColor: '#409eff',
  disabled: false,
  size: 'default',
  value: false,
  onColor: '#13ce66',
  offColor: '#ff4949',
  loading: false,
  width: 40,
  activeIcon: '',
  label: '开关',
  showLabel: true,
  labelAlignment: 'start',
  labelPosition: 'left',
  labelWidth: '30',
  labelFontColor: 'rgba(0, 0, 0, 0.80)',
  labelFontSize: 14,
  style: {
    position: 'absolute',
    width: 100,
    height: 42,
    visibility: 'inherit',
    top: 73,
    left: 501,
    color: 'rgba(255, 255, 255, 1)',
  },
};
