export default {
  options: [
    { label: '选项1', value: '1' },
    { label: '选项2', value: '2' },
  ],
  name: 'tabs',
  layout: 'top',
  tabStyle: '',
  stretch: false,
  value: '1',
  color: 'rgba(0, 0, 0, 0.40)',
  selectedColor: '#409eff',
  selectedBgColor: 'rgba(0, 0, 0, 0.40)',
  tabItemHeight: '40px',
  tabPadding: '20px',
  style: {
    width: 378,
    height: 39,
    border: 0,
    position: 'absolute',
    visibility: 'inherit',
    top: 73,
    left: 501,
    borderTopWidth: '0',
    borderRightWidth: '0',
    borderBottomWidth: '0',
    borderLeftWidth: '0',
  },
};
