export default {
  text: '时间选择器',
  currentTime: true,
  placeholder: '请选择',
  format: 'YYYY-MM-DD HH:mm:ss',
  dateType: 'datetime',
  disabled: false,
  label: '时间选择框',
  showLabel: true,
  labelAlignment: 'start',
  labelPosition: 'left',
  labelWidth: '20',
  validation: [],
  style: {
    width: 400,
    height: 32,
    color: '#287CE8',
    labelColor: '#606266',
    labelFontSize: '14',
    inputActiveColor: '#287CE8',
    inputBorderColor: '#dcdfe6',
    inputBackgroundColor: 'transparent',
    position: 'absolute',
    top: 73,
    left: 501,
    visibility: 'inherit',
    borderTopWidth: '0',
    borderRightWidth: '0',
    borderBottomWidth: '0',
    borderLeftWidth: '0',
  },
};
