export default {
  clearable: false,
  value: '',
  disabled: false,
  maxlength: '',
  placeholder: '请输入',
  prefixText: '',
  showWordLimit: false,
  suffixText: '',
  inputType: 'text',
  label: '输入框',
  showLabel: true,
  labelAlignment: 'start',
  labelPosition: 'left',
  labelWidth: '15',
  validation: [
    {
      pattren: /^\S+/,
      message: '不能为空',
    },
  ],
  style: {
    width: 400,
    height: 32,
    color: '#287CE8',
    position: 'absolute',
    visibility: 'inherit',
    top: 73,
    left: 501,
    borderTopWidth: '0',
    borderRightWidth: '0',
    borderBottomWidth: '0',
    borderLeftWidth: '0',
  },
  labelColor: '#606266',
  labelFontSize: '14',
  inputActiveColor: '#287CE8',
  inputBorderColor: '#dcdfe6',
  inputTextColor: '#606266',
  inputBackgroundColor: 'transparent',
  inputAppendBgColor: '#f5f7fa',
  inputAppendColor: '#909399',
};
