export default {
  text: '下拉菜单',
  columns: [
    {
      label: '选项1',
      value: '1',
    },
    {
      label: '选项2',
      value: '2',
    },
    {
      label: '选项3',
      value: '3',
    },
  ],
  value: '',
  placeholder: '请选择',
  disabled: false,
  label: '选择框',
  showLabel: true,
  labelAlignment: 'start',
  labelPosition: 'left',
  labelWidth: '15',
  validation: [],
  style: {
    width: 400,
    height: 32,
    color: '#287CE8',
    labelColor: '#606266',
    labelFontSize: '14',
    inputTextColor: '#606266',
    inputActiveColor: '#287CE8',
    inputBorderColor: '#dcdfe6',
    inputBgColor: 'rgba(255, 255, 255, 0)',
    position: 'absolute',
    top: 73,
    left: 501,
    visibility: 'inherit',
    borderTopWidth: '0',
    borderRightWidth: '0',
    borderBottomWidth: '0',
    borderLeftWidth: '0',
  },
};
